services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
      target: app
    image: transmorpher-prod-8.4/app
    networks:
      - traefik
      - internal
    depends_on:
      mariadb:
        condition: service_healthy
      traefik:
        condition: service_started
    environment:
      PULLPREVIEW: true
      PULLPREVIEW_FIRST_RUN: ${PULLPREVIEW_FIRST_RUN}
      APP_URL: https://transmorpher.${PULLPREVIEW_PUBLIC_DNS}
      CLIENT_CONTAINER_NAME: ${COMPOSE_PROJECT_NAME}-amigor
    volumes:
      - 'storage:/var/www/html/storage'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`transmorpher.${PULLPREVIEW_PUBLIC_DNS}`)'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=production'

  worker-transcoding:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
      target: transcoder
    image: transmorpher-prod-8.4/transcoder
    networks:
      - traefik
      - internal
    depends_on:
      mariadb:
        condition: service_healthy
      traefik:
        condition: service_started
    environment:
      APP_URL: https://transmorpher.${PULLPREVIEW_PUBLIC_DNS}
      CONTAINER_ROLE: worker
      SERVICE_INSTANCES: ${VIDEO_TRANSCODING_WORKERS_AMOUNT:-1}
      QUEUE: video-transcoding
    volumes:
      - 'storage:/var/www/html/storage'

  worker-client-notifications:
    image: transmorpher-prod-8.4/app
    networks:
      - traefik
      - internal
    depends_on:
      mariadb:
        condition: service_healthy
      traefik:
        condition: service_started
    environment:
      APP_URL: https://transmorpher.${PULLPREVIEW_PUBLIC_DNS}
      CONTAINER_ROLE: worker
      SERVICE_INSTANCES: 1
      QUEUE: client-notifications
    volumes:
      - 'storage:/var/www/html/storage'

  worker-email:
    image: transmorpher-prod-8.4/app
    networks:
      - traefik
      - internal
    depends_on:
      mariadb:
        condition: service_healthy
      traefik:
        condition: service_started
    environment:
      APP_URL: https://transmorpher.${PULLPREVIEW_PUBLIC_DNS}
      CONTAINER_ROLE: worker
      SERVICE_INSTANCES: 1
      QUEUE: email
    volumes:
      - 'storage:/var/www/html/storage'

  scheduler:
    image: transmorpher-prod-8.4/app
    environment:
      APP_URL: https://transmorpher.${PULLPREVIEW_PUBLIC_DNS}
      CONTAINER_ROLE: scheduler
    networks:
      - internal
    volumes:
      - 'storage:/var/www/html/storage'

  mariadb:
    image: 'mariadb:lts-noble'
    environment:
      MARIADB_DATABASE: '${DB_DATABASE}'
      MARIADB_USER: '${DB_USERNAME}'
      MARIADB_PASSWORD: '${DB_PASSWORD}'
      MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mariadb:/var/lib/mysql'
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      retries: 3
      timeout: 5s

########################################################################## Amigor ##########################################################################

  amigor:
    container_name: ${COMPOSE_PROJECT_NAME}-amigor
    image: 'cybexwebdev/transmorpher-amigor'
    networks:
      - traefik
      - internal
    depends_on:
      amigor-mysql:
        condition: service_healthy
      traefik:
        condition: service_started
    environment:
      PULLPREVIEW: true
      PULLPREVIEW_FIRST_RUN: ${PULLPREVIEW_FIRST_RUN}
      TRANSMORPHER_WEB_DELIVERY_BASE_URL: https://transmorpher.${PULLPREVIEW_PUBLIC_DNS}
      TRANSMORPHER_WEB_API_BASE_URL: https://transmorpher.${PULLPREVIEW_PUBLIC_DNS}/api
      APP_URL: https://${PULLPREVIEW_PUBLIC_DNS}
    volumes:
      - 'amigor-storage:/var/www/html/amigor/storage'
      - '.env.amigor:/var/www/html/amigor/.env'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}-amigor.rule=Host(`${PULLPREVIEW_PUBLIC_DNS}`)'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}-amigor.tls=true'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}-amigor.tls.certresolver=production'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}-amigor.priority=1'
      # Protect the root with Basic Auth.
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}-amigor-root.rule=Host(`${PULLPREVIEW_PUBLIC_DNS}`) && Path(`/`)'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}-amigor-root.middlewares=htpasswd'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}-amigor-root.tls=true'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}-amigor-root.tls.certresolver=production'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}-amigor-root.priority=2'
      - 'traefik.http.middlewares.htpasswd.basicauth.usersfile=/.htpasswd'

  amigor-mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'amigor'
      MYSQL_USER: 'amigor'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'amigor-mysql:/var/lib/mysql'
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-ppassword" ]
      retries: 3
      timeout: 5s

########################################################################## Traefik ##########################################################################

  traefik:
    image: traefik:mimolette
    ports:
      - '80:80'
      - '443:443'
    environment:
      TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: false
      TRAEFIK_LOG: true
      TRAEFIK_LOG_FILEPATH: '/logs/traefik.log'
      TRAEFIK_LOG_LEVEL: DEBUG
      TRAEFIK_API: false
      TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION: true
      TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION_ACME_EMAIL: 'cloud@cybex-online.com'
      TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION_ACME_CASERVER: 'https://acme-v02.api.letsencrypt.org/directory'
      TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION_ACME_STORAGE: '/letsencrypt/acme.json'
      TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION_ACME_HTTPCHALLENGE: true
      TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION_ACME_HTTPCHALLENGE_ENTRYPOINT: web
      TRAEFIK_ENTRYPOINTS_WEB: true
      TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: ':80'
      TRAEFIK_ENTRYPOINTS_WEB_HTTP: true
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO: websecure
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: https
      TRAEFIK_ENTRYPOINTS_WEBSECURE: true
      TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: ':443'
      TRAEFIK_PROVIDERS_DOCKER: true
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: false
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./storage/letsencrypt:/letsencrypt
      - ./storage/logs:/logs
      - ./.htpasswd:/.htpasswd:ro
    networks:
      - traefik

########################################################################## Networks & Volumes ##########################################################################

networks:
  internal:
    internal: true
  traefik:
    name: traefik

volumes:
  mariadb:
    driver: local
  amigor-mysql:
    driver: local
  storage:
    driver: local
  amigor-storage:
    driver: local
