x-common: &common
  volumes:
    - '.:/var/www'
  depends_on:
    - mariadb
  networks:
    - shared
    - internal

x-local: &common-env
  APP_ENV: local

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}
    <<: *common
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: transmorpher-dev-8.4/app
    environment:
      <<: *common-env
      CONTAINER_ROLE: web
    volumes:
      - '.:/var/www'
      - 'home:/home/www'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.test`)'
      - 'traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80'

  testing:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: transmorpher-dev-8.4/app
    environment:
      APP_ENV: testing
      CONTAINER_ROLE: app
    volumes:
      - '.:/var/www'
      - 'home:/home/www'
    networks:
      - shared
      - internal
    depends_on:
      - mariadb_testing

  worker-transcoding:
    <<: *common
    image: cybexwebdev/php-laravel:8.4-transcoder
    environment:
      <<: *common-env
      CONTAINER_ROLE: worker
      SERVICE_INSTANCES: ${VIDEO_TRANSCODING_WORKERS_AMOUNT:-1}
      QUEUE: video-transcoding

  worker-client-notifications:
    <<: *common
    image: cybexwebdev/php-laravel:8.4-alpine
    environment:
      <<: *common-env
      CONTAINER_ROLE: worker
      SERVICE_INSTANCES: 1
      QUEUE: client-notifications

  scheduler:
    <<: *common
    image: cybexwebdev/php-laravel:8.4-alpine
    environment:
      <<: *common-env
      CONTAINER_ROLE: scheduler
    networks:
      - internal

  mariadb:
    image: 'mariadb:lts-noble'
    environment:
      MARIADB_DATABASE: '${DB_DATABASE}'
      MARIADB_USER: '${DB_USERNAME}'
      MARIADB_PASSWORD: '${DB_PASSWORD}'
      MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mariadb:/var/lib/mysql'
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      retries: 3
      timeout: 5s

  mariadb_testing:
    image: 'mariadb:lts-noble'
    environment:
      MARIADB_DATABASE: 'transmorpher_test'
      MARIADB_USER: 'transmorpher_test'
      MARIADB_PASSWORD: 'transmorpher_test'
      MARIADB_ROOT_PASSWORD: 'transmorpher_test'
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      retries: 3
      timeout: 5s

networks:
  internal:
    internal: true
  shared:
    external: true
volumes:
  mariadb:
    driver: local
  home:
    driver: local
