# For more information: https://laravel.com/docs/sail
version: '3.8'
services:
    app:
        container_name: ${DOCKER_CONTAINER_NAME:-transmorpher}
        build:
            context: ./docker/${DOCKER_PHP_VERSION:-8.2}
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-${DOCKER_PHP_VERSION:-8.2}/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - shared
            - internal
        depends_on:
            - mysql
            - mysql_testing
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.${DOCKER_CONTAINER_NAME:-transmorpher}.rule=Host(`${DOCKER_CONTAINER_DOMAIN:-transmorpher.test}`)'
            - 'traefik.http.services.${DOCKER_CONTAINER_NAME:-transmorpher}.loadbalancer.server.port=80'
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - shared
            - internal
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    mysql_testing:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: 'transmorpher_test'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'transmorpher_test'
            MYSQL_USER: 'transmorpher_test'
            MYSQL_PASSWORD: 'transmorpher_test'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - internal
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
networks:
    internal:
        internal: true
    shared:
        external: true
volumes:
    sail-mysql:
        driver: local
