name: Docker Image CI

on:
  pull_request:
    types: [ labeled, synchronize, closed ]

env:
  DOCKER_REPOSITORY: cybexwebdev/transmorpher

jobs:
  pr-images:
    if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'create docker image') && github.event.action != 'closed' }}
    runs-on: ubuntu-latest

    steps:
      # Needed for caching, fails without.
      - name: Setup Docker Buildx
        # https://github.com/docker/setup-buildx-action
        uses: docker/setup-buildx-action@v4

      - name: Get branch name
        run: echo "BRANCH_NAME=$(echo ${{ github.head_ref }} | tr / -)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        # https://github.com/docker/login-action
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Specify docker image tags
        id: meta
        # https://github.com/docker/metadata-action
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.DOCKER_REPOSITORY }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ env.BRANCH_NAME }}

      - name: Build and push
        uses: docker/bake-action@v7
        env:
          CACHE_KEY: ${{ env.BRANCH_NAME }}
        with:
          files: |
            docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          targets: default
          push: true
          sbom: true
          provenance: true

  delete-pr-images:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        run: echo "BRANCH_NAME=$(echo ${{ github.head_ref }} | tr / -)" >> $GITHUB_ENV

      - name: Delete docker images which were created
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${{ secrets.DOCKERHUB_USERNAME }}'", "password": "'${{ secrets.DOCKERHUB_TOKEN }}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
          curl --fail-with-body -s -X DELETE -H "Authorization: Bearer ${TOKEN}" https://hub.docker.com/v2/repositories/${{ env.DOCKER_REPOSITORY }}/tags/${{ env.BRANCH_NAME }}-app/
          curl --fail-with-body -s -X DELETE -H "Authorization: Bearer ${TOKEN}" https://hub.docker.com/v2/repositories/${{ env.DOCKER_REPOSITORY }}/tags/${{ env.BRANCH_NAME }}-transcoder/
