name: Tests

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
  workflow_dispatch:

jobs:
  execute-tests:
    name: Setup testing environment and execute tests
    # https://github.com/cybex-gmbh/github-workflows/blob/main/.github/workflows/tests.yml
    uses: cybex-gmbh/github-workflows/.github/workflows/tests.yml@fix/tests-cache-fails
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.4 ]
        laravel: [ 12.* ]
        dependency-version: [ prefer-stable ]
    with:
      PHP_VERSION: ${{ matrix.php }}
      LARAVEL_VERSION: ${{ matrix.laravel }}
      DEPENDENCY_VERSION: ${{ matrix.dependency-version }}
      DATABASE_NAME: transmorpher_test
      DATABASE_IMAGE: mariadb:lts-noble
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_CONNECTION: mariadb
      DATABASE_OPTIONS: "--health-cmd=\"healthcheck.sh --connect --innodb_initialized\" --health-interval=10s --health-timeout=5s --health-retries=3"
      # Imagick is set up with PHP, Ghostscript is needed for PDFs.
      BREW_FORMULAS: ghostscript jpegoptim optipng pngquant gifsicle webp ffmpeg mariadb
